version: "3.5"
services:
  boot:
    image: clj-builder:boot
    environment:
      APP_HOME: "${PWD}"
    build:
      context: .
      args:
        APP_HOME: "${PWD}"
    volumes:
      - ./src:${PWD}/src
      - ./test:${PWD}/test
      - ./log:${PWD}/log
    command: repl
    ports:
      - "5888:5888"
